# Generated by Django 2.1.2 on 2018-10-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('relevant_experience', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='JobReferral',
            fields=[
                ('jobapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jobapplicationportal.JobApplication')),
                ('referrer_name', models.CharField(max_length=50)),
                ('referrer_email', models.EmailField(max_length=50)),
            ],
            bases=('jobapplicationportal.jobapplication',),
        ),
    ]
